"""Initial tables

Revision ID: dbf9ae06cf2e
Revises: 95112783ac24
Create Date: 2025-01-30 04:41:45.566806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf9ae06cf2e'
down_revision: Union[str, None] = '95112783ac24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_user_id_fkey', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'], source_schema='mychat', referent_schema='mychat')
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_user_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['chat_id'], source_schema='mychat', referent_schema='mychat')
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'], source_schema='mychat', referent_schema='mychat')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'messages', schema='mychat', type_='foreignkey')
    op.drop_constraint(None, 'messages', schema='mychat', type_='foreignkey')
    op.create_foreign_key('messages_user_id_fkey', 'messages', 'users', ['user_id'], ['id'])
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['chat_id'])
    op.drop_constraint(None, 'chats', schema='mychat', type_='foreignkey')
    op.create_foreign_key('chats_user_id_fkey', 'chats', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
