"""Initial tables

Revision ID: 95112783ac24
Revises: 
Create Date: 2025-01-30 01:50:45.684637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95112783ac24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('chats_user_id_fkey', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'], source_schema='mychat', referent_schema='mychat')
    op.alter_column('messages', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['chat_id'], source_schema='mychat', referent_schema='mychat')
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'], source_schema='mychat', referent_schema='mychat')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', schema='mychat', type_='foreignkey')
    op.drop_constraint(None, 'messages', schema='mychat', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['chat_id'])
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'chats', schema='mychat', type_='foreignkey')
    op.create_foreign_key('chats_user_id_fkey', 'chats', 'users', ['user_id'], ['id'])
    op.alter_column('chats', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
